name: project-ticket-system
command: ["python", "app.py"]
env:
  - name: FLASK_ENV
    value: production

  - name: LAKEBASE_ENDPOINT
    value: projects/project-ticket-system/branches/production/endpoints/primary

resources:
  - name: lakebase-db
    lakebase:
      postgres:
        branch: projects/project-ticket-system/branches/production
        database: databricks_postgres